# Name of the workflow
name: Deploy

# Trigger: triggered by a push event on the main branch
on:
  push:
    branches:
      - main

# Has 2 jobs: build and deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest # The job runs on the latest version of Ubuntu
    env:
      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}

    steps:
      # checks out the repo code
      - name: Checkout repo
        uses: actions/checkout@v3
      # setup node.js environment
      - name: Setup Node
        uses: actions/setup-node@v3
      # install pnpm
      - name: Install pnpm
        run: npm install -g pnpm
      # install the project dependencies
      - name: Install dependencies
        run: pnpm install
      # build project using pnpm build script
      - name: Build project
        run: pnpm run build
      # upload the build files from the ./dist directory
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
